[build]
command = "pnpm nx affected -t=build --exclude='*,!slides' --verbose"
publish = "apps/slides/dist"

[build.environment]
NODE_VERSION = "22"

[[redirects]]
from = "/.well-known/*"
to = "/.well-known/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
