language: en-CA

tone_instructions: Please maintain a professional tone with constructive feedback.

early_access: false

enable_free_tier: true

reviews:
  profile: chill
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_placeholder: '@coderabbitai summary'
  auto_title_placeholder: '@coderabbitai'
  review_status: true
  poem: true
  collapse_walkthrough: true
  sequence_diagrams: true
  abort_on_close: true
  auto_review:
    enabled: true
    auto_incremental_review: true
    drafts: true

chat:
  auto_reply: true

knowledge_base:
  opt_out: false
  learnings:
    scope: auto
  issues:
    scope: auto
  pull_requests:
    scope: auto
