import { CUHACKING_2025_WEBSITE_URL } from '@website-e2e/shared/constants'

export const CUHACKING_WEBSITE_ABOUT_URL = `${CUHACKING_2025_WEBSITE_URL}/#about`
export const CUHACKING_WEBSITE_EVENTS_URL = `${CUHACKING_2025_WEBSITE_URL}/#events`
export const CUHACKING_WEBSITE_SPONSORS_URL = `${CUHACKING_2025_WEBSITE_URL}/#sponsors`
export const CUHACKING_WEBSITE_FAQ_URL = `${CUHACKING_2025_WEBSITE_URL}/#faq`
