import { TRPCReactProvider } from '../lib/trpc/react'
import './global.css'

export const metadata = {
  title: 'Welcome to portal',
  description: 'Generated by create-nx-workspace',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <TRPCReactProvider>
          {children}
        </TRPCReactProvider>
      </body>
    </html>
  )
}
