[build]
command = "pnpm nx migrate:run axiom; pnpm nx build axiom --verbose"
# command = "pnpm nx build axiom --verbose"
# publish = "apps/axiom/dist/apps/axiom"
publish = "apps/axiom/.next"

[[plugins]]
package = "@netlify/plugin-nextjs"
