name: Other
description: Create an issue that doesn't fit into any other category
title: 'type(scope-of-issue): description'
body:
  - type: checkboxes
    id: search
    attributes:
      label: Search checkbox
      description: Insufficiently described issues will be closed, so please provide as much information as possible
      options:
        - label: Have you searched for similar [issues](https://github.com/cuhacking/2025/issues)?
  - type: dropdown
    id: platforms
    attributes:
      label: Platforms
      multiple: true
      options:
        - all
        - Website
        - Docs
        - Portal
      default: 0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of what needs to be done
    validations:
      required: true
