version: '3.9'
services:
  app:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    ports:
      - '8000:8000'
    image: app
    container_name: app
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
    depends_on:
      - db
    networks:
      - hackathon-network
  db:
    image: postgres:13
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    networks:
      - hackathon-network
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
networks:
  hackathon-network:
    driver: bridge
volumes:
  db-data:
