export enum EIcons {
  ARROW = 'arrow',
  LINK = 'link',
  CALENDAR = 'calendar',
  CHEVRON_DOWN = 'chevron_down',
  PHONE = 'phone',
  CHEVRON_UP = 'chevron_up',
  HAMBURGER = 'hamburger',
  GITHUB_GREEN = 'github_green',
  INSTAGRAM_GREEN = 'instagram_green',
  LINKEDIN_GREEN = 'linkedin_green',
  LINKTREE_GREEN = 'linktree_green',
  EMAIL_GREEN = 'email_green',
  DISCORD_GREEN = 'discord_green',
  DOCS_GREEN = 'docs_green',
  FIGMA_GREEN = 'figma_green',
  GITHUB_WHITE = 'github_white',
  INSTAGRAM_WHITE = 'instagram_white',
  LINKEDIN_WHITE = 'linkedin_white',
  LINKTREE_WHITE = 'linktree_white',
  EMAIL_WHITE = 'email_white',
  DISCORD_WHITE = 'discord_white',
  DOCS_WHITE = 'docs_white',
  FIGMA_WHITE = 'figma_white',
}
