// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getSite(args?: GetSiteArgs, opts?: pulumi.InvokeOptions): Promise<GetSiteResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("netlify:index/getSite:getSite", {
        "id": args.id,
        "name": args.name,
        "teamSlug": args.teamSlug,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSite.
 */
export interface GetSiteArgs {
    id?: string;
    name?: string;
    teamSlug?: string;
}

/**
 * A collection of values returned by getSite.
 */
export interface GetSiteResult {
    readonly customDomain: string;
    readonly domainAliases: string[];
    readonly gitDeployKey: string;
    readonly id: string;
    readonly name: string;
    readonly teamSlug: string;
}
export function getSiteOutput(args?: GetSiteOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSiteResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("netlify:index/getSite:getSite", {
        "id": args.id,
        "name": args.name,
        "teamSlug": args.teamSlug,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSite.
 */
export interface GetSiteOutputArgs {
    id?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    teamSlug?: pulumi.Input<string>;
}
