// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getSites(args?: GetSitesArgs, opts?: pulumi.InvokeOptions): Promise<GetSitesResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("netlify:index/getSites:getSites", {
        "teamSlug": args.teamSlug,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSites.
 */
export interface GetSitesArgs {
    teamSlug?: string;
}

/**
 * A collection of values returned by getSites.
 */
export interface GetSitesResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly sites: outputs.GetSitesSite[];
    readonly teamSlug: string;
}
export function getSitesOutput(args?: GetSitesOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSitesResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("netlify:index/getSites:getSites", {
        "teamSlug": args.teamSlug,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getSites.
 */
export interface GetSitesOutputArgs {
    teamSlug?: pulumi.Input<string>;
}
