// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The provider type for the netlify package. By default, resources use package-wide configuration
 * settings, however an explicit `Provider` instance may be created and passed during resource
 * construction to achieve fine-grained programmatic control over provider settings. See the
 * [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
 */
export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'netlify';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === "pulumi:providers:" + Provider.__pulumiType;
    }

    /**
     * The default team ID to use for resources that require a team ID or a team slug. Warning: Changing this value may not
     * trigger recreation of resources.
     */
    public readonly defaultTeamId!: pulumi.Output<string | undefined>;
    /**
     * The default team slug to use for resources that require a team ID or a team slug. Warning: Changing this value may not
     * trigger recreation of resources.
     */
    public readonly defaultTeamSlug!: pulumi.Output<string | undefined>;
    /**
     * Defaults to: https://api.netlify.com
     */
    public readonly endpoint!: pulumi.Output<string | undefined>;
    /**
     * Read: https://docs.netlify.com/api/get-started/#authentication , will use the `NETLIFY_API_TOKEN` environment variable
     * if not set.
     */
    public readonly token!: pulumi.Output<string | undefined>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            resourceInputs["defaultTeamId"] = args ? args.defaultTeamId : undefined;
            resourceInputs["defaultTeamSlug"] = args ? args.defaultTeamSlug : undefined;
            resourceInputs["endpoint"] = args ? args.endpoint : undefined;
            resourceInputs["token"] = args?.token ? pulumi.secret(args.token) : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["token"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Provider.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    /**
     * The default team ID to use for resources that require a team ID or a team slug. Warning: Changing this value may not
     * trigger recreation of resources.
     */
    defaultTeamId?: pulumi.Input<string>;
    /**
     * The default team slug to use for resources that require a team ID or a team slug. Warning: Changing this value may not
     * trigger recreation of resources.
     */
    defaultTeamSlug?: pulumi.Input<string>;
    /**
     * Defaults to: https://api.netlify.com
     */
    endpoint?: pulumi.Input<string>;
    /**
     * Read: https://docs.netlify.com/api/get-started/#authentication , will use the `NETLIFY_API_TOKEN` environment variable
     * if not set.
     */
    token?: pulumi.Input<string>;
}
