// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class SiteMetricsSettings extends pulumi.CustomResource {
    /**
     * Get an existing SiteMetricsSettings resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SiteMetricsSettingsState, opts?: pulumi.CustomResourceOptions): SiteMetricsSettings {
        return new SiteMetricsSettings(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'netlify:index/siteMetricsSettings:SiteMetricsSettings';

    /**
     * Returns true if the given object is an instance of SiteMetricsSettings.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SiteMetricsSettings {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SiteMetricsSettings.__pulumiType;
    }

    public /*out*/ readonly lastUpdated!: pulumi.Output<string>;
    /**
     * Enable real user metrics. Warning: This might incur a cost on certain plans.
     */
    public readonly realUserMetrics!: pulumi.Output<boolean | undefined>;
    /**
     * Enable site analytics. Warning: This might incur a cost on certain plans. Note: You must wait 10 minutes before
     * disabling after enabling.
     */
    public readonly siteAnalytics!: pulumi.Output<boolean | undefined>;
    public readonly siteId!: pulumi.Output<string>;

    /**
     * Create a SiteMetricsSettings resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SiteMetricsSettingsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SiteMetricsSettingsArgs | SiteMetricsSettingsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SiteMetricsSettingsState | undefined;
            resourceInputs["lastUpdated"] = state ? state.lastUpdated : undefined;
            resourceInputs["realUserMetrics"] = state ? state.realUserMetrics : undefined;
            resourceInputs["siteAnalytics"] = state ? state.siteAnalytics : undefined;
            resourceInputs["siteId"] = state ? state.siteId : undefined;
        } else {
            const args = argsOrState as SiteMetricsSettingsArgs | undefined;
            if ((!args || args.siteId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'siteId'");
            }
            resourceInputs["realUserMetrics"] = args ? args.realUserMetrics : undefined;
            resourceInputs["siteAnalytics"] = args ? args.siteAnalytics : undefined;
            resourceInputs["siteId"] = args ? args.siteId : undefined;
            resourceInputs["lastUpdated"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SiteMetricsSettings.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering SiteMetricsSettings resources.
 */
export interface SiteMetricsSettingsState {
    lastUpdated?: pulumi.Input<string>;
    /**
     * Enable real user metrics. Warning: This might incur a cost on certain plans.
     */
    realUserMetrics?: pulumi.Input<boolean>;
    /**
     * Enable site analytics. Warning: This might incur a cost on certain plans. Note: You must wait 10 minutes before
     * disabling after enabling.
     */
    siteAnalytics?: pulumi.Input<boolean>;
    siteId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a SiteMetricsSettings resource.
 */
export interface SiteMetricsSettingsArgs {
    /**
     * Enable real user metrics. Warning: This might incur a cost on certain plans.
     */
    realUserMetrics?: pulumi.Input<boolean>;
    /**
     * Enable site analytics. Warning: This might incur a cost on certain plans. Note: You must wait 10 minutes before
     * disabling after enabling.
     */
    siteAnalytics?: pulumi.Input<boolean>;
    siteId: pulumi.Input<string>;
}
