// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class SiteDomainSettings extends pulumi.CustomResource {
    /**
     * Get an existing SiteDomainSettings resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SiteDomainSettingsState, opts?: pulumi.CustomResourceOptions): SiteDomainSettings {
        return new SiteDomainSettings(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'netlify:index/siteDomainSettings:SiteDomainSettings';

    /**
     * Returns true if the given object is an instance of SiteDomainSettings.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SiteDomainSettings {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SiteDomainSettings.__pulumiType;
    }

    public readonly branchDeployCustomDomain!: pulumi.Output<string | undefined>;
    public readonly customDomain!: pulumi.Output<string | undefined>;
    public readonly deployPreviewCustomDomain!: pulumi.Output<string | undefined>;
    public readonly domainAliases!: pulumi.Output<string[]>;
    public /*out*/ readonly lastUpdated!: pulumi.Output<string>;
    public readonly siteId!: pulumi.Output<string>;

    /**
     * Create a SiteDomainSettings resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SiteDomainSettingsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SiteDomainSettingsArgs | SiteDomainSettingsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SiteDomainSettingsState | undefined;
            resourceInputs["branchDeployCustomDomain"] = state ? state.branchDeployCustomDomain : undefined;
            resourceInputs["customDomain"] = state ? state.customDomain : undefined;
            resourceInputs["deployPreviewCustomDomain"] = state ? state.deployPreviewCustomDomain : undefined;
            resourceInputs["domainAliases"] = state ? state.domainAliases : undefined;
            resourceInputs["lastUpdated"] = state ? state.lastUpdated : undefined;
            resourceInputs["siteId"] = state ? state.siteId : undefined;
        } else {
            const args = argsOrState as SiteDomainSettingsArgs | undefined;
            if ((!args || args.siteId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'siteId'");
            }
            resourceInputs["branchDeployCustomDomain"] = args ? args.branchDeployCustomDomain : undefined;
            resourceInputs["customDomain"] = args ? args.customDomain : undefined;
            resourceInputs["deployPreviewCustomDomain"] = args ? args.deployPreviewCustomDomain : undefined;
            resourceInputs["domainAliases"] = args ? args.domainAliases : undefined;
            resourceInputs["siteId"] = args ? args.siteId : undefined;
            resourceInputs["lastUpdated"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SiteDomainSettings.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering SiteDomainSettings resources.
 */
export interface SiteDomainSettingsState {
    branchDeployCustomDomain?: pulumi.Input<string>;
    customDomain?: pulumi.Input<string>;
    deployPreviewCustomDomain?: pulumi.Input<string>;
    domainAliases?: pulumi.Input<pulumi.Input<string>[]>;
    lastUpdated?: pulumi.Input<string>;
    siteId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a SiteDomainSettings resource.
 */
export interface SiteDomainSettingsArgs {
    branchDeployCustomDomain?: pulumi.Input<string>;
    customDomain?: pulumi.Input<string>;
    deployPreviewCustomDomain?: pulumi.Input<string>;
    domainAliases?: pulumi.Input<pulumi.Input<string>[]>;
    siteId: pulumi.Input<string>;
}
