// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class SiteFirewallTrafficRules extends pulumi.CustomResource {
    /**
     * Get an existing SiteFirewallTrafficRules resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SiteFirewallTrafficRulesState, opts?: pulumi.CustomResourceOptions): SiteFirewallTrafficRules {
        return new SiteFirewallTrafficRules(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'netlify:index/siteFirewallTrafficRules:SiteFirewallTrafficRules';

    /**
     * Returns true if the given object is an instance of SiteFirewallTrafficRules.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SiteFirewallTrafficRules {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SiteFirewallTrafficRules.__pulumiType;
    }

    public /*out*/ readonly lastUpdated!: pulumi.Output<string>;
    public readonly published!: pulumi.Output<outputs.SiteFirewallTrafficRulesPublished>;
    public readonly siteId!: pulumi.Output<string>;
    public /*out*/ readonly teamId!: pulumi.Output<string>;
    public readonly unpublished!: pulumi.Output<outputs.SiteFirewallTrafficRulesUnpublished>;

    /**
     * Create a SiteFirewallTrafficRules resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SiteFirewallTrafficRulesArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SiteFirewallTrafficRulesArgs | SiteFirewallTrafficRulesState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SiteFirewallTrafficRulesState | undefined;
            resourceInputs["lastUpdated"] = state ? state.lastUpdated : undefined;
            resourceInputs["published"] = state ? state.published : undefined;
            resourceInputs["siteId"] = state ? state.siteId : undefined;
            resourceInputs["teamId"] = state ? state.teamId : undefined;
            resourceInputs["unpublished"] = state ? state.unpublished : undefined;
        } else {
            const args = argsOrState as SiteFirewallTrafficRulesArgs | undefined;
            if ((!args || args.published === undefined) && !opts.urn) {
                throw new Error("Missing required property 'published'");
            }
            if ((!args || args.siteId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'siteId'");
            }
            if ((!args || args.unpublished === undefined) && !opts.urn) {
                throw new Error("Missing required property 'unpublished'");
            }
            resourceInputs["published"] = args ? args.published : undefined;
            resourceInputs["siteId"] = args ? args.siteId : undefined;
            resourceInputs["unpublished"] = args ? args.unpublished : undefined;
            resourceInputs["lastUpdated"] = undefined /*out*/;
            resourceInputs["teamId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SiteFirewallTrafficRules.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering SiteFirewallTrafficRules resources.
 */
export interface SiteFirewallTrafficRulesState {
    lastUpdated?: pulumi.Input<string>;
    published?: pulumi.Input<inputs.SiteFirewallTrafficRulesPublished>;
    siteId?: pulumi.Input<string>;
    teamId?: pulumi.Input<string>;
    unpublished?: pulumi.Input<inputs.SiteFirewallTrafficRulesUnpublished>;
}

/**
 * The set of arguments for constructing a SiteFirewallTrafficRules resource.
 */
export interface SiteFirewallTrafficRulesArgs {
    published: pulumi.Input<inputs.SiteFirewallTrafficRulesPublished>;
    siteId: pulumi.Input<string>;
    unpublished: pulumi.Input<inputs.SiteFirewallTrafficRulesUnpublished>;
}
