// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class SiteCollaborationSettings extends pulumi.CustomResource {
    /**
     * Get an existing SiteCollaborationSettings resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SiteCollaborationSettingsState, opts?: pulumi.CustomResourceOptions): SiteCollaborationSettings {
        return new SiteCollaborationSettings(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'netlify:index/siteCollaborationSettings:SiteCollaborationSettings';

    /**
     * Returns true if the given object is an instance of SiteCollaborationSettings.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SiteCollaborationSettings {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SiteCollaborationSettings.__pulumiType;
    }

    public /*out*/ readonly lastUpdated!: pulumi.Output<string>;
    public readonly netlifyDrawerInBranchDeploys!: pulumi.Output<boolean>;
    public readonly netlifyDrawerInDeployPreviews!: pulumi.Output<boolean>;
    public readonly netlifyHeadsUpDisplay!: pulumi.Output<boolean>;
    public readonly siteId!: pulumi.Output<string>;

    /**
     * Create a SiteCollaborationSettings resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SiteCollaborationSettingsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SiteCollaborationSettingsArgs | SiteCollaborationSettingsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SiteCollaborationSettingsState | undefined;
            resourceInputs["lastUpdated"] = state ? state.lastUpdated : undefined;
            resourceInputs["netlifyDrawerInBranchDeploys"] = state ? state.netlifyDrawerInBranchDeploys : undefined;
            resourceInputs["netlifyDrawerInDeployPreviews"] = state ? state.netlifyDrawerInDeployPreviews : undefined;
            resourceInputs["netlifyHeadsUpDisplay"] = state ? state.netlifyHeadsUpDisplay : undefined;
            resourceInputs["siteId"] = state ? state.siteId : undefined;
        } else {
            const args = argsOrState as SiteCollaborationSettingsArgs | undefined;
            if ((!args || args.netlifyDrawerInBranchDeploys === undefined) && !opts.urn) {
                throw new Error("Missing required property 'netlifyDrawerInBranchDeploys'");
            }
            if ((!args || args.netlifyDrawerInDeployPreviews === undefined) && !opts.urn) {
                throw new Error("Missing required property 'netlifyDrawerInDeployPreviews'");
            }
            if ((!args || args.netlifyHeadsUpDisplay === undefined) && !opts.urn) {
                throw new Error("Missing required property 'netlifyHeadsUpDisplay'");
            }
            if ((!args || args.siteId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'siteId'");
            }
            resourceInputs["netlifyDrawerInBranchDeploys"] = args ? args.netlifyDrawerInBranchDeploys : undefined;
            resourceInputs["netlifyDrawerInDeployPreviews"] = args ? args.netlifyDrawerInDeployPreviews : undefined;
            resourceInputs["netlifyHeadsUpDisplay"] = args ? args.netlifyHeadsUpDisplay : undefined;
            resourceInputs["siteId"] = args ? args.siteId : undefined;
            resourceInputs["lastUpdated"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SiteCollaborationSettings.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering SiteCollaborationSettings resources.
 */
export interface SiteCollaborationSettingsState {
    lastUpdated?: pulumi.Input<string>;
    netlifyDrawerInBranchDeploys?: pulumi.Input<boolean>;
    netlifyDrawerInDeployPreviews?: pulumi.Input<boolean>;
    netlifyHeadsUpDisplay?: pulumi.Input<boolean>;
    siteId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a SiteCollaborationSettings resource.
 */
export interface SiteCollaborationSettingsArgs {
    netlifyDrawerInBranchDeploys: pulumi.Input<boolean>;
    netlifyDrawerInDeployPreviews: pulumi.Input<boolean>;
    netlifyHeadsUpDisplay: pulumi.Input<boolean>;
    siteId: pulumi.Input<string>;
}
