// https://github.com/shefing/payload-tools/tree/main/packages/authorization
/* eslint-disable node/prefer-global/process */

const LEVEL_OF_STUDY= [
    { value: 'secondary', label: 'Secondary / High School' },
    {
      value: 'undergraduate2Year',
      label: 'College',
    },
    {
      value: 'undergraduate3PlusYear',
      label: 'Undergraduate',
    },
    {
      value: 'graduate',
      label: 'Graduate University',
    },
    { value: 'codeSchool', label: 'Code School / Bootcamp' },
    {
      value: 'vocationalTrade',
      label: 'Trade Program or Apprenticeship',
    },
    { value: 'postDoctorate', label: 'Post Doctorate' },
    { value: 'other', label: 'Other' },
    { value: 'notStudent', label: 'I’m not currently a student' },
    { value: 'preferNotToAnswer', label: 'Prefer not to answer' },
  ]

const FIELD_OF_STUDY= [
    {
      value: 'computerScience',
      label: 'Computer science, computer engineering, or software engineering',
    },
    {
      value: 'anotherEngineering',
      label:
        'Another engineering discipline (such as civil, electrical, mechanical, etc.)',
    },
    {
      value: 'informationSystems',
      label:
        'Information systems, information technology, or system administration',
    },
    {
      value: 'naturalScience',
      label: 'A natural science (such as biology, chemistry, physics, etc.)',
    },
    { value: 'mathematicsStatistics', label: 'Mathematics or statistics' },
    { value: 'webDevelopment', label: 'Web development or web design' },
    {
      value: 'business',
      label:
        'Business discipline (such as accounting, finance, marketing, etc.)',
    },
    {
      value: 'humanities',
      label:
        'Humanities discipline (such as literature, history, philosophy, etc.)',
    },
    {
      value: 'socialScience',
      label:
        'Social science (such as anthropology, psychology, political science, etc.)',
    },
    {
      value: 'fineArts',
      label:
        'Fine arts or performing arts (such as graphic design, music, studio art, etc.)',
    },
    {
      value: 'healthScience',
      label: 'Health science (such as nursing, pharmacy, radiology, etc.)',
    },
    { value: 'other', label: 'Other' },
    { value: 'undecided', label: 'Undecided / No Declared Major' },
    {
      value: 'noMajors',
      label: 'My school does not offer majors / primary areas of study',
    },
    { value: 'preferNotToAnswer', label: 'Prefer not to answer' },
  ]
const GENDER = [
  { value: 'male', label: 'Male' },
  { value: 'female', label: 'Female' },
  { value: 'non-binary', label: 'Non-Binary' },
  { value: 'transgender', label: 'Transgender' },
  { value: 'genderfluid', label: 'Genderfluid' },
  { value: 'agender', label: 'Agender' },
  { value: 'two-spirit', label: 'Two-Spirit' },
  { value: 'other', label: 'Other' },
  { value: 'prefer-not-to-say', label: 'Prefer not to say' },
]

function toCamelCase(sentence: string) {
  return sentence
    .replace(/[^a-z0-9 ]/gi, '') // Remove non-alphanumeric characters
    .split(' ')
    .map((word, index) =>
      index === 0
        ? word.toLowerCase()
        : word.charAt(0).toUpperCase() + word.slice(1).toLowerCase(),
    )
    .join('')
}

export const RELATIONSHIPS = [
  { label: 'Parent', value: 'parent' },
  { label: 'Spouse', value: 'spouse' },
  { label: 'Sibling', value: 'sibling' },
  { label: 'Child', value: 'child' },
  { label: 'Guardian', value: 'guardian' },
  { label: 'Grandparent', value: 'grandparent' },
  { label: 'Aunt/Uncle', value: 'auntUncle' },
  { label: 'Cousin', value: 'cousin' },
  { label: 'Friend', value: 'friend' },
  { label: 'Neighbor', value: 'neighbor' },
  { label: 'Colleague', value: 'colleague' },
  { label: 'Doctor', value: 'doctor' },
  { label: 'Caregiver', value: 'caregiver' },
  { label: 'Legal Representative', value: 'legalRepresentative' },
  { label: 'Other', value: 'other' },
]

const ALL_SCHOOLS = [
  'Memorial University of Newfoundland',
  'University of Prince Edward Island',
  'Acadia University',
  'Acadia Divinity College',
  'Atlantic School of Theology',
  'Cape Breton University',
  'Dalhousie University',
  'University of King\'s College',
  'Mount Saint Vincent University',
  'Nova Scotia College of Art and Design University (NSCAD)',
  'Université Sainte-Anne',
  'St. Francis Xavier University',
  'Saint Mary\'s University',
  'Mount Allison University',
  'University of New Brunswick',
  'Université de Moncton (parent)',
  'St. Thomas University',
  'Bishop\'s University',
  'McGill University',
  'Université de Montréal',
  'Polytechnique Montréal',
  'École des hautes études commerciales',
  'Université Laval',
  'Université de Sherbrooke',
  'Concordia University',
  'Université du Québec à Chicoutimi',
  'Université du Québec à Montréal',
  'Université du Québec en Abitibi-Témiscamingue',
  'Université du Québec à Trois-Rivières',
  'Université du Québec en Outaouais',
  'Université du Québec, École nationale d\'administration publique (ENAP)',
  'Université du Québec, Institut national de la recherche scientifique',
  'Université du Québec à Rimouski',
  'Université du Québec, École de technologie supérieure',
  'Université du Québec, Télé-université du Québec (TÉLUQ)',
  'Brock University',
  'Concordia Lutheran Theological Seminary',
  'Carleton University',
  'Dominican University College/Collège Universitaire Dominicain',
  'University of Guelph',
  'Lakehead University',
  'Laurentian University of Sudbury/Université Laurentienne de Sudbury',
  'McMaster University',
  'Nipissing University',
  'University of Ottawa',
  'Saint-Paul University/Université Saint-Paul',
  'Queen\'s University',
  'Ryerson University',
  'University of Toronto',
  'St. Augustine\'s Seminary',
  'University of St. Michael\'s College',
  'University of Trinity College',
  'Victoria University',
  'Knox College',
  'Wycliffe College',
  'Regis College',
  'Trent University',
  'University of Waterloo',
  'St. Jerome\'s University',
  'Renison University College',
  'Conrad Grebel University College',
  'University of Western Ontario',
  'Brescia University College',
  'Huron University College',
  'King\'s College',
  'Wilfred Laurier University',
  'University of Windsor',
  'York University',
  'Ontario College of Art and Design',
  'University of Ontario Institute of Technology',
  'Algoma University College',
  'University of Sudbury',
  'Université de Hearst',
  'Huntington University',
  'Thorneloe University',
  'Brandon University',
  'Canadian Mennonite University',
  'University of Manitoba',
  'Université de Saint-Boniface',
  'University of Winnipeg',
  'University of Regina',
  'Campion College',
  'Luther College',
  'University of Saskatchewan ',
  'College of Emmanuel and St. Chad',
  'Lutheran Theological Seminary',
  'St. Andrew\'s College',
  'St. Thomas More College',
  'Horizon College & Seminary',
  'University of Alberta',
  'Athabasca University',
  'University of Calgary',
  'Burman University',
  'Concordia University of Edmonton',
  'University of Lethbridge',
  'The King\'s University College',
  'Ambrose University',
  'Grant MacEwan University',
  'Mount Royal University',
  'University of British Columbia',
  'University of Northern British Columbia',
  'Royal Roads University',
  'Simon Fraser University',
  'University of Victoria',
  'Thompson Rivers University',
  'Capilano University',
  'Vancouver Island University',
  'Emily Carr University of Art and Design',
  'Kwantlen Polytechnic University',
  'University of the Fraser Valley',
  'Yukon University',
  'Other',
]

const SCHOOLS = ALL_SCHOOLS.map(school => ({
  label: school,
  value: toCamelCase(school),
}))

import type { CollectionConfig } from 'payload'
import { admins,
         isSameUser,
         adminsAndUser,
         anyone,
  // checkRole
} from '@/db/access'
// import { authenticated, isAdminFieldLevel } from '@/db/access'
import { navAccordions } from '@/db/collections/navAccordions'

export const Users: CollectionConfig = {
  slug: 'users',
  // auth: true,
  auth: {
    disableLocalStrategy: {
      enableFields: true,
      optionalPassword: true,
    },
  },
  access: {
    // admin: ({ req: { user } }) => checkRole(['admin'], user),
    admin: anyone,
    read: adminsAndUser,
    create: anyone,
    update: (req) => { return adminsAndUser(req) || isSameUser(req)  },
    delete: admins,
  },
  // hooks: {
  //   afterChange: [loginAfterCreate],
  // },
  admin: {
    livePreview: {
      url: `${process.env.CUHACKING_2025_PORTAL_LOCAL_URL}/profile`,
      breakpoints: [
        {
          label: 'Mobile',
          name: 'mobile',
          width: 320,
          height: 568,
        },
      ],
    },
    group: navAccordions.featured,
    useAsTitle: 'preferredDisplayName',
    defaultColumns: [
      'avatar',
      'preferredDisplayName',
      'pronouns',
      'cell',
      'email',
      'dietaryRestrictions',
      'linkedinEmailVerified',
      'updatedAt',
      'createdAt',
      'id',
    ],
    pagination: {
      defaultLimit: 50,
      limits: [10, 20, 50],
    },
  },
  versions: {
    drafts: true,
    maxPerDoc: 3,
  },
  fields: [
    {
      name: 'group',
      type: 'relationship',
      relationTo: 'groups'
    },
    {
      type: 'collapsible',
      label: ({ data }) => data?.title || 'Personal Information',
      fields: [
        { name: 'preferredDisplayName', type: 'text', label: 'Display Name' },
        { name: 'firstName', type: 'text', label: 'First Name' },
        { name: 'middleName', type: 'text', label: 'Middle Name' },
        { name: 'lastName', type: 'text', label: 'Last Name' },
        {
          name: 'pronouns',
          type: 'select',
          label: 'Pronouns',
          options: [
            { label: 'He/Him', value: 'he/him' },
            { label: 'She/Her', value: 'she/her' },
            { label: 'They/Them', value: 'they/them' },
            { label: 'Other', value: 'other' },
          ],
        },
        { name: 'phoneNumber', type: 'text', label: 'Phone Number'  },
        { name: 'age', type: 'number', label: 'Age'  },
        { name: 'gender', type: 'select', label: 'Gender', options: GENDER  },
        {
          name: 'avatar',
          type: 'upload',
          relationTo: 'media',
          label: 'Avatar',
        },
      ],
    },
    {
      name: 'agreedToTerms',
      type: 'checkbox',
      label: 'Agreed to Terms and Conditions',
      admin: { position: 'sidebar'},
    },
    {
      name: 'resumeLink',
      type: 'text',
      label: 'Resume Link',
      admin: { position: 'sidebar'},
    },
    {
      name: 'dietaryRestrictions',
      type: 'select'  ,
      label: '🍽 Dietary Restrictions',
      admin: { position: 'sidebar'  },
      options: [
        { label: '🥗 Vegetarian', value: 'vegetarian' },
        { label: '🌱 Vegan', value: 'vegan' },
        { label: '🕌 Halal', value: 'halal' },
        { label: '✡ Kosher', value: 'kosher' },
        { label: '🐟 Pescatarian', value: 'pescatarian' },
        { label: '🥛 Dairy-Free', value: 'dairy-free' },
        { label: '🌾 Gluten-Free', value: 'gluten-free' },
        { label: '🍤 Shellfish-Free', value: 'shellfish-free' },
        { label: '🥜 Nut-Free', value: 'nut-free' },
        { label: '🥩 Keto', value: 'keto' },
        { label: '🧀 Low-Lactose', value: 'low-lactose' },
        { label: '🍚 Low-Carb', value: 'low-carb' },
        { label: '🍖 Paleo', value: 'paleo' },
        { label: '⚡ High-Protein', value: 'high-protein' },
        { label: '🌿 Raw Vegan', value: 'raw-vegan' },
        { label: '🥒 Whole30', value: 'whole30' },
        { label: '🍵 Fasting', value: 'fasting' },
        { label: '❓ Other', value: 'other' },
      ],
      hasMany: true,
    },
    {
      name: 'allergies',
      type: 'select',
      label: '⚠ Allergies',
      admin: { position: 'sidebar',  },
      options: [
        { label: '🥜 Peanuts', value: 'peanuts' },
        { label: '🌰 Tree Nuts', value: 'tree-nuts' },
        { label: '🥛 Dairy', value: 'dairy' },
        { label: '🌾 Gluten', value: 'gluten' },
        { label: '🍤 Shellfish', value: 'shellfish' },
        { label: '🐟 Fish', value: 'fish' },
        { label: '🍯 Soy', value: 'soy' },
        { label: '🍳 Eggs', value: 'eggs' },
        { label: '🥩 Red Meat', value: 'red-meat' },
        { label: '🌽 Corn', value: 'corn' },
        { label: '🥦 Sulfites', value: 'sulfites' },
        { label: '🍎 Fruits', value: 'fruits' },
        { label: '🥕 Vegetables', value: 'vegetables' },
        { label: '☕ Caffeine', value: 'caffeine' },
        { label: '🍯 Honey', value: 'honey' },
        { label: '❓ Other', value: 'other' },
      ],
      hasMany: true,
    },
    {
      name: 'tshirtSize',
      type: 'select',
      label: 'T-Shirt Size',
      admin: { position: 'sidebar',  },
      options: [
        { label: 'XS', value: 'xs' },
        { label: 'S', value: 's' },
        { label: 'M', value: 'm' },
        { label: 'L', value: 'l' },
        { label: 'XL', value: 'xl' },
        { label: '2XL', value: '2xl' },
        { label: '3XL', value: '3xl' },
      ],
    },
    {
      label: 'Emergency Contact',
      type: 'collapsible',
      fields: [
        { name: 'emergencyContactFullName', type: 'text', label: 'Full Name' },
        { name: 'emergencyContactPhoneNumber', type: 'text', label: 'Cell' },
        { name: 'emergencyContactEmail', type: 'email', label: 'Email Address' },
        { name: 'emergencyContactRelationship', type: 'select', label: 'Relationship', options: RELATIONSHIPS },
      ],
    },
    {
      label: 'Education',
      type: 'collapsible',
      fields: [
        { name: 'institution', type: 'select', options: SCHOOLS, label: 'Institution' },
        { name: 'fieldOfStudy', type: 'select', options: FIELD_OF_STUDY, label: 'Field of Study' },
        { name: 'degree', type: 'select', label: 'Degree', options: LEVEL_OF_STUDY },
        { name: 'expectedGraduationDate', type: 'date', label: 'Expected Graduation Date' },
        { name: 'yearStanding', type: 'select', options:['1', '2', '3', '4', '5', '6+'] },
      ],
    },
    {
      type: 'collapsible',
      label: ({ data }) => data?.title || 'Brand & Socials',
      admin: { position: 'sidebar',  },
      fields: [
        {
          name: 'website',
          type: 'text',
          label: 'Personal Website',
        },
        {
          name: 'behance',
          type: 'text',
          label: 'Behance',
          admin: { readOnly: true },
        },
        {
          type: 'collapsible',
          label: 'LinkedIn',
          fields: [
            {
              name: 'linkedinVanity',
              type: 'text',
              label: 'Handle',
              admin: { readOnly: true },
            },
            {
              name: 'linkedinId',
              type: 'text',
              label: 'ID',
              admin: {
                condition: () => {
                  return false
                },
              },
            },
            {
              name: 'linkedinEmailVerified',
              label: 'Verified Email',
              type: 'checkbox',
              admin: {
                readOnly: true,
              },
            },
            {
              name: 'linkedinLocale',
              type: 'text',
              admin: {
                readOnly: true,
              },
            },
          ],
        },
        {
          type: 'collapsible',
          label: 'GitHub',
          admin: { readOnly: true },
          fields: [
            {
              name: 'githubUrl',
              type: 'text',
              admin: {
                condition: () => {
                  return false
                },
              },
            },
            {
              name: 'githubEmail',
              type: 'email',
            },
            {
              name: 'githubId',
              type: 'text',
              admin: {
                condition: () => {
                  return false
                },
              },
            },
            {
              name: 'githubAvatarUrl',
              type: 'text',
              admin: {
                condition: () => {
                  return false
                },
              },
            },
            {
              name: 'githubType',
              type: 'text',
              admin: {
                condition: () => {
                  return false
                },
              },
            },
            {
              name: 'githubHtmlUrl',
              type: 'text',
            },
            {
              name: 'githubName',
              type: 'text',
              admin: {
                condition: () => {
                  return false
                },
              },
            },
            {
              name: 'githubBlog',
              type: 'text',
            },
            {
              name: 'githubLocation',
              type: 'text',
              admin: {
                condition: () => {
                  return false
                },
              },
            },
            {
              name: 'githubHireable',
              type: 'text',
              admin: {
                condition: () => {
                  return false
                },
              },
            },
            {
              name: 'githubPublicRepos',
              type: 'text',
            },
            {
              name: 'githubLinkedin',
              type: 'text',
            },
            {
              name: 'githubInstagram',
              type: 'text',
            },
          ],
        },
        {
          type: 'collapsible',
          label: 'Discord',
          fields: [
            {
              name: 'discordUsername',
              type: 'text',
            },
            {
              name: 'discordGlobalName',
              type: 'text',
            },
            {
              name: 'discordVerified',
              type: 'checkbox',
            },
            {
              name: 'discordDiscriminator',
              type: 'text',
            },
            {
              name: 'discordLocale',
              type: 'text',
            },
            {
              name: 'discordId',
              type: 'text',
              admin: {
                readOnly: true,
                  condition: () => {
                    return false
                  }
              },
            },
          ],
        },
        {
          type: 'collapsible',
          label: 'Google',
          fields: [
            { name: 'googleEmail', type: 'email' },
            {
              name: 'googleEmailVerified',
              type: 'checkbox',
            },
          ],
        },
      ],
    },
  ],
  timestamps: true,
}

export const userData = [
  {
    email: 'adam@example.com',
    firstName: 'Adam',
    lastName: 'Said',
    preferredDisplayName: 'Adam Said',
    pronouns: 'he/him',
    mediaUrl: 'https://media.licdn.com/dms/image/v2/D4E03AQFzuS67keWDSA/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1730318417047?e=1745452800&v=beta&t=cqIsgTOVOxdRiT464rfT4EGhaTROdf4s5Y9WHr5egIY',
    linkedinHandle: 'adamsaid-',
    tshirtSize: 'm',
  },
  {
    email: 'ryan@example.com',
    firstName: 'Ryan',
    lastName: 'Awad',
    preferredDisplayName: 'Ryan Awad',
    pronouns: 'he/him',
    mediaUrl: 'https://media.licdn.com/dms/image/v2/D4E03AQGvSOt-3nfCNQ/profile-displayphoto-shrink_800_800/B4EZNUwaleHwAc-/0/1732293799188?e=1745452800&v=beta&t=-Vec3wCaAaOfozQBaBeykLG8lU8X9xyqJrCGpx1Xv1s',
    linkedinHandle: 'ryanawad',
    tshirtSize: 'l',
  },
  {
    email: 'isabella@example.com',
    firstName: 'Isabella',
    lastName: 'Nguyen',
    preferredDisplayName: 'Isabella Nguyen',
    pronouns: 'she/her',
    mediaUrl: 'https://lh3.googleusercontent.com/pw/AP1GczNFEtJwT8NugAIGttYyro85pVB-eKyComthbU_c4kGsv21Q0bJsULJ7CIqerhtB52RwzO6KUb0gR2yvRv3kw9HBgoXUlfTOIxV5rIZMR-EjeTm6M7OAnW694YuNzg2N2YZssPpqV-gOxNjU1sx_nvkk=w973-h1460-s-no-gm?authuser=0',
    linkedinHandle: 'isabella-vi-nguyen',
    tshirtSize: 's',
  },
  {
    email: 'aashna@example.com',
    firstName: 'Aashna',
    lastName: 'Verma',
    preferredDisplayName: 'Aashna Verma',
    pronouns: 'she/her',
    mediaUrl: 'https://lh3.googleusercontent.com/pw/AP1GczPnBFA29FY5cEvpxDMzb0rnTvbdywy16kJirlRUMfi7PGCI1SjER-sMPnJBSlAENzJe-CMQfCZvW83maSGDL5UIaRaKayf_o3hTkfQLwaxF7W3H7F1SHQ3N_kMkKW6Jgat1BRwKYBtUmRRSZ5P_pLDy=w973-h1460-s-no-gm?authuser=0',
    website: 'https://aashna-verma.github.io',
    linkedinHandle: 'aashna-verma-000',
    tshirtSize: 'm',
  },
  {
    email: 'esra@example.com',
    firstName: 'Esra',
    lastName: 'Marwa',
    preferredDisplayName: 'Esra Marwa',
    pronouns: 'she/her',
    mediaUrl: 'https://lh3.googleusercontent.com/pw/AP1GczPDYyAyTFY3XGiLSuohOG0fg0URX2EqAG0Pvf8UA5I58ftgOUxAds7LZA5cljIAd5rpXu7O9BgujVHKaf5P4zCynV0HOE-ZQki_tSASJKi_meWiFIlCL4epkdeIfUT_Ua86cXibS_VRfCT3tjh-_hnD=w973-h1460-s-no-gm?authuser=0',
    linkedinHandle: 'esra-abdulwahab-947b332ab',
    tshirtSize: 'l',
  },
  {
    email: 'selena@example.com',
    firstName: 'Selena',
    lastName: 'Quang',
    preferredDisplayName: 'Selena Quang',
    pronouns: 'she/her',
    mediaUrl: 'https://lh3.googleusercontent.com/pw/AP1GczNSNXmJAJq-pyJA5_NRV6vq4-lA0BtnfXBsEGL0-2QTQB78UphzSVZCjoXOalGEYNLrlyfOYDFFjgqjx8hqHR0oPiZ_ckSn4FSmQy7oH72WikWjYI5dyMXFznaGm-AuzM6M9XLfEJH6ydg815u8xovH=w973-h1460-s-no-gm?authuser=0',
    linkedinHandle: 'selena-quang-0aa9422b1',
    tshirtSize: 'm',
  },
  {
    email: 'raef@example.com',
    firstName: 'Raef',
    lastName: 'Sarofiem',
    preferredDisplayName: 'Raef Sarofiem',
    pronouns: 'he/him',
    mediaUrl: 'https://lh3.googleusercontent.com/pw/AP1GczOUErtyx85CgCIu6vkCViP0ujZ1qcOA48udyCHzj6zSVtZz_Z5Y16c_LH5LQ2MyjoinY9Zg-ZwHMISCjwtliTlqnPC8BH1i3LVRH4jwGQSEPRmL8cvKgQWi5zcTUDWtoJogjPynnuUqEL0nxySKM515=w973-h1460-s-no-gm?authuser=0',
    linkedinHandle: 'raefsarofiem',
    tshirtSize: 'm',
  },
  {
    email: 'ajaan@example.com',
    firstName: 'Ajaan',
    lastName: 'Nalliah',
    preferredDisplayName: 'Ajaan Nalliah',
    pronouns: 'he/him',
    mediaUrl: 'https://lh3.googleusercontent.com/pw/AP1GczP2FdXEKCmBRIUeELhu8wyDN2wj7JV3aey-93-2aQBTn4SEiuRO5D7c-FGtbjGUl6kaTuO1aM-NgoEqIQ7NsCiQ1J7oO-qXw-7cmFlzAZp4ewTLyVMTEIphNbmfjdewy1AZK3RqRe1njMdn_flWIyVr=w973-h1460-s-no-gm?authuser=0',
    linkedinHandle: 'ajaan-nalliah-6b2b1029b',
    tshirtSize: 'l',
  },
  {
    email: 'ishar@example.com',
    firstName: 'Ishar',
    lastName: 'Ghura',
    preferredDisplayName: 'Ishar Ghura',
    pronouns: 'he/him',
    mediaUrl: 'https://lh3.googleusercontent.com/pw/AP1GczOTN9YofQ1eEGQsOnC5cw4pavbNtHlfLZ-MPDk-a0_RUEHvyGUxir2h31kryxozxX6fxpCqnPKBRurhw7V0cKdKJFAJwEKw8vbLryW5Egj9bzDASiIUS9GadaRLymelEeEn8Un5aOkP-3fZtPmEUpSN=w973-h1460-s-no-gm?authuser=0',
    linkedinHandle: 'ishar-ghura',
    tshirtSize: 'm',
  },
  {
    email: 'avantika@example.com',
    firstName: 'Avantika',
    lastName: 'Rao',
    preferredDisplayName: 'Avantika Rao',
    pronouns: 'she/her',
    mediaUrl: 'https://lh3.googleusercontent.com/pw/AP1GczNn4H0AZVNdXnuHk-QiSQt7RIM_SLEeJfmuEXUSxsmAGTrdBt6wciGlts0sQx94tE6NqpM0CrKBS3gAeyip1i5zzy6AUc_tuCKduG2W8078N8cgvauXsYnvd_vuChrLmdfjklkGYSZ5a_OPIv3S-QP3=w973-h1460-s-no-gm?authuser=0',
    linkedinHandle: 'avantika-rao-01a1b2204',
    tshirtSize: 's',
  },
  {
    email: 'khyonc@example.com',
    firstName: 'Khyonc',
    lastName: 'Brown',
    preferredDisplayName: 'Khyonc Brown',
    pronouns: 'he/him',
    mediaUrl: 'https://lh3.googleusercontent.com/pw/AP1GczMdX_wPGEMl4Fys82bTIZquBOqA1kAKUhitvhxBVcLH3YylTMo-X7gLUXpoZJ2ROri5srSiCrMr1wcIhxiE7gF1RoL8pr8GGsnr1FGP9klgpf_cxQDy7cgV_jMQKUaSx_sXACY8j8GgIbeEmyNrVtXN=w973-h1460-s-no-gm?authuser=0',
    linkedinHandle: 'khyonc-browne-7a3518258',
    tshirtSize: 'l',
  },
  {
    email: 'muhammad.maisam@example.com',
    firstName: 'Muhammad',
    lastName: 'Maisam',
    preferredDisplayName: 'Muhammad Maisam',
    pronouns: 'he/him',
    mediaUrl: 'https://lh3.googleusercontent.com/pw/AP1GczMX5cvMkW4aiUvggwjZ07th8FXyjymISJNx2Bw6avmV0UNU7w7pXG1pIc7h-vfJmRFv5m2U8Ejmwei5S6_oI78lnAUjqH62ctwnXeY3A8wtbncAlALHdJsfwf2GKvLFkzEXu6Paep0n3XCqXx5aRL9-=w973-h1460-s-no-gm?authuser=0',
    linkedinHandle: 'muhammadmaisam01',
    tshirtSize: 'm',
  },
  {
    email: 'trista.wang@example.com',
    firstName: 'Trista',
    lastName: 'Wang',
    preferredDisplayName: 'Trista Wang',
    pronouns: 'she/her',
    mediaUrl: 'https://lh3.googleusercontent.com/pw/AP1GczPGPIRoLROduZYMRNtuFxmks2p4IjXOZm92QR-gYA_2xeJdpjOkALSIyM4o2y7WskyV_FyIX4O5uiCT3gfpbUmS1DszeFMkMPgWyBVoulVw2aV3JmRTSUSfcc3P8eduT0maOMCKaOpv72rkF5fj9zy1=w973-h1460-s-no-gm?authuser=0',
    linkedinHandle: 'tristaxwang',
    tshirtSize: 's',
  },
  {
    email: 'joel.cherian@example.com',
    firstName: 'Joel',
    lastName: 'Cherian',
    preferredDisplayName: 'Joel Cherian',
    pronouns: 'he/him',
    mediaUrl: 'https://lh3.googleusercontent.com/pw/AP1GczM-zryfkT9NiSB_8RnpoI7CXp2jSuKYadSiiXm7XdMwovTHwfr7R6hrdr5UYLmlL7D1PSIqGs_RrJnRzdNxfuc0RUW3KEqXBmB4e9KfVxuOTKTeQqW4MhWLkbOaakogSzZ-teCL4QhR22SyaeXNRglw=w973-h1460-s-no-gm?authuser=0',
    linkedinHandle: 'joel-v-cherian',
    tshirtSize: 'm',
  },
  {
    email: 'lily.salem@example.com',
    firstName: 'Lily',
    lastName: 'Salem',
    preferredDisplayName: 'Lily Salem',
    pronouns: 'she/her',
    mediaUrl: 'https://lh3.googleusercontent.com/pw/AP1GczPaA1DMXJzWJwJSnF55TbKfP1-picLG0qlt8rDSq6ygR7u-gDfTP4ljEnlVC9C12NoR25t47xSlmLmFkG6TRtuvZGgfzpVdm96pU5SjBmNoNm4F-Ro0icEkZQvsuw_4C7auN9oIU_ihx2rbuKhqO4b1=w1020-h1460-s-no-gm?authuser=0',
    linkedinHandle: 'lily-s-396190262',
    tshirtSize: 's',
  },
  {
    email: 'ngan.cao@example.com',
    firstName: 'Ngan',
    lastName: 'Cao',
    preferredDisplayName: 'Ngan Cao',
    pronouns: 'she/her',
    mediaUrl: 'https://media.licdn.com/dms/image/v2/D4E03AQGnH32IzAJMjw/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1726748243924?e=1745452800&v=beta&t=UVQ6JmZ3xh_Yt7rkp9gdKtPiCggL8J6wGQ6UGp1K20M',
    linkedinHandle: 'nganc',
    tshirtSize: 'm',
  },
  {
    email: 'giancarlo.salvador@example.com',
    firstName: 'Giancarlo',
    lastName: 'Salvador',
    preferredDisplayName: 'Giancarlo Salvador',
    pronouns: 'he/him',
    mediaUrl: 'https://lh3.googleusercontent.com/pw/AP1GczMHEqnKFRc0o94jAfmkCDxHUPQYnzzF7f37PSZBBt4F5tR53GyAaWiQVxb3kY1aiEW4CTYAaCxPeyqTuW9dfQYRhry0cjZ1DYmKo5wly-hLb3JkiRTMlWF0NcddNa3WShYaq1TZ1yBHSBXaUdgfEZSB=w973-h1460-s-no-gm?authuser=0',
    linkedinHandle: 'giancarlo-salvador-310696203',
    tshirtSize: 'm',
  },
  {
    email: 'bashar.kazma@example.com',
    firstName: 'Bashar',
    lastName: 'Kazma',
    preferredDisplayName: 'Bashar Kazma',
    pronouns: 'he/him',
    linkedinHandle: 'bashar-kazma-a7223b208',
    tshirtSize: 'm',
  },
  {
    email: 'sheila.sieyoji@example.com',
    firstName: 'Sheila',
    lastName: 'Sieyoji',
    preferredDisplayName: 'Sheila Sieyoji',
    pronouns: 'she/her',
    linkedinHandle: 'sheila-sieyoji',
    tshirtSize: 's',
  },
  {
    email: 'muskaan.opel@example.com',
    firstName: 'Muskaan',
    lastName: 'Opel',
    preferredDisplayName: 'Muskaan Opel',
    pronouns: 'she/her',
    mediaUrl: 'https://media.licdn.com/dms/image/v2/D4D03AQGMskAh2EGdWw/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1725570711218?e=1745452800&v=beta&t=-414xN3eIx4I4FZw5CFDBPj24a8PskeP3Nbs4DdBUFA',
    linkedinHandle: 'muskaan-opel',
    tshirtSize: 'm',
  },
  {
    email: 'raaed.mirza@example.com',
    firstName: 'Raaed',
    lastName: 'Mirza',
    preferredDisplayName: 'Raaed Mirza',
    pronouns: 'he/him',
    mediaUrl: 'https://lh3.googleusercontent.com/pw/AP1GczPKmUy7qyv72vZaucsZjFY92U-E-w4RAEBll0dLqc8lz9YLkg5pKpLWB_lb0Z2Dti8d02zcJzbEdZ-WQXENWyxzWtKoo1rvJAo-Xa51FOKvdTVfgtWHQHiojeryJisIWDVrSglj4siHLTGygZACd9xM=w973-h1460-s-no-gm?authuser=0',
    linkedinHandle: 'raaed-mirza-96a01324b',
    tshirtSize: 'm',
  },
  {
    email: 'rayhaan.farooq@example.com',
    firstName: 'Rayhaan',
    lastName: 'Farooq',
    preferredDisplayName: 'Rayhaan Farooq',
    pronouns: 'he/him',
    mediaUrl: 'https://media.licdn.com/dms/image/v2/D5603AQE2yMZOidak5Q/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1732724878570?e=1745452800&v=beta&t=AD0vMOORXiunKiB-ZQwyLC_No1_abXecrfPhcOxUTWk',
    linkedIn: 'rayhaanfarooq',
    tshirtSize: 'l',
  },
  {
    email: 'akshavi.baskaran@example.com',
    firstName: 'Akshavi',
    lastName: 'Baskaran',
    preferredDisplayName: 'Akshavi Baskaran',
    pronouns: 'she/her',
    mediaUrl: 'https://lh3.googleusercontent.com/pw/AP1GczMtupVAte8rqZLg0jSPpRQIY9OAZmX5DGgUlK8ESqUpopi3Ad6Sg8Ky1fM_B-Wi5VvE-KAs6-746keRYOJP_M4VH7vk5XXC4UmW49OXp9-l9OBgFUHy8eYrbIbYBsJ_8ED-TrBw6fn4osLXU775EIjH=w960-h1460-s-no-gm?authuser=0',
    linkedIn: 'akshavibaskaran',
    tshirtSize: 's',
  },
  {
    email: 'saim.hashmi@example.com',
    firstName: 'Saim',
    lastName: 'Hashmi',
    preferredDisplayName: 'Saim Hashmi',
    pronouns: 'he/him',
    mediaUrl: 'https://media.licdn.com/dms/image/v2/D5603AQEf51mAN7q4xQ/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1728509244535?e=1745452800&v=beta&t=MbqxW4OOk2bhxwWfb3IVqhEzdJPrOqDU7e39surPgWI',
    website: 'https://saimhashmi-nextjsportfolio.vercel.app',
    tshirtSize: 'm',
  },
  {
    email: 'zesan.rahim@example.com',
    firstName: 'Zesan',
    lastName: 'Rahim',
    preferredDisplayName: 'Zesan Rahim',
    pronouns: 'he/him',
    mediaUrl: 'https://media.licdn.com/dms/image/v2/D4D03AQHFX2P2vrmj_Q/profile-displayphoto-shrink_800_800/B4DZRwAy7tHUAo-/0/1737046044937?e=1745452800&v=beta&t=_iQMOdKj38mYnta5U5HqlAJvVo8EoLS5VrltU2ZeVsA',
    linkedinHandle: 'zesanrahim',
    tshirtSize: 'm',
  },
  {
    email: 'hasith.dealwis@example.com',
    firstName: 'Hasith',
    lastName: 'De Alwis',
    preferredDisplayName: 'Hasith De Alwis',
    pronouns: 'he/him',
    mediaUrl: 'https://lh3.googleusercontent.com/pw/AP1GczPvNrBhbm4qKthN16w7uBgmQXxLowqA04GLe7BhhF2pQ_nO6UEzJl-8is_C63omPxR1RNkGZzRgasuqxGDM8qZ2ZX1qIguJ6HDJB4gFQkyP8rbxa4P5qL63JEbwrtc5mRO2JnMC_tukw6e0XGg5GBhm=w973-h1460-s-no-gm?authuser=0',
    website: 'https://hasithdev.com',
    tshirtSize: 'm',
  },
  {
    email: 'julie.wechsler@example.com',
    firstName: 'Julie',
    lastName: 'Wechsler',
    preferredDisplayName: 'Julie Wechsler',
    pronouns: 'she/her',
    mediaUrl: 'https://media.licdn.com/dms/image/v2/D5603AQHrtYolc2r2iw/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1703135371921?e=1745452800&v=beta&t=lYyF6NByBPFYo6neENClyRtD8p8ZIxKsT3RFOqB5Ijk',
    linkedinHandle: 'julie-wechsler',
    tshirtSize: 's',
  },
  {
    email: 'nathan.coulas@example.com',
    firstName: 'Nathan',
    lastName: 'Coulas',
    preferredDisplayName: 'Nathan Coulas',
    pronouns: 'he/him',
    mediaUrl: 'https://media.licdn.com/dms/image/v2/D4E03AQFSKW7ZVp_YAg/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1687537705169?e=1745452800&v=beta&t=Td3td2WntyFGv_rUMgpWAlRwny80gYXOjqI0PAXVXWk',
    website: 'https://www.nathancoulas.com',
    tshirtSize: 'm',
  },
  {
    email: 'aires.zheng@example.com',
    firstName: 'Aires',
    lastName: 'Zheng',
    preferredDisplayName: 'Aires Zheng',
    pronouns: 'he/him',
    mediaUrl: 'https://media.licdn.com/dms/image/v2/D5603AQFpPEcbSQ-DjQ/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1705438318025?e=2147483647&v=beta&t=DFLOlD53THYXX5-xh9NRNkYAQoBBOgYBmHvINxfzNoo',
    linkedinHandle: 'aireszheng',
    tshirtSize: 'm',
  },
  {
    email: 'charelle.constantino@example.com',
    firstName: 'Charelle',
    middleName: 'Jazmin',
    lastName: 'Constantino',
    preferredDisplayName: 'Charelle Jazmin Constantino',
    pronouns: 'she/her',
    mediaUrl: 'https://media.licdn.com/dms/image/v2/D4E03AQHW2k19bHl7xg/profile-displayphoto-shrink_800_800/B4EZSZUBQwHAAo-/0/1737738950436?e=1745452800&v=beta&t=z7rW44W4R2XNLuOL4P9jur_pLFdtP_OqLD7ELkaML1s',
    linkedinHandle: 'charelleconstantino',
    tshirtSize: 's',
  },
  {
    email: 'hamid.siddiqi@example.com',
    firstName: 'Hamid',
    lastName: 'Siddiqi',
    preferredDisplayName: 'Hamid Siddiqi',
    pronouns: 'he/him',
    mediaUrl: 'https://cdn.myportfolio.com/454dcab6-47f4-42e5-a6de-9ea8205bf3bb/6ed09481-ff18-4136-977e-760af1a5532c_rw_1200.png?h=31b2afa3e7428a16b774e49ebfc64c52',
    website: 'https://hamidsiddiqi.myportfolio.com/about-me',
    linkedIn: 'hamidsiddiqi',
    tshirtSize: 'm',
  },
  {
    email: 'hairuo.chen@example.com',
    firstName: 'Hairuo',
    lastName: 'Chen',
    preferredDisplayName: 'Hairuo Chen',
    pronouns: 'they/them',
    mediaUrl: 'https://media.licdn.com/dms/image/v2/D4E03AQHuLKGQCfsneg/profile-displayphoto-shrink_800_800/B4EZQ9F0BmHEAc-/0/1736191721870?e=1745452800&v=beta&t=-yeZeKRThoN-lXEWIVRYAh3rTbOK3shX49DadNCv0u4',
    website: 'https://hairuochen.framer.website/',
    linkedinHandle: 'hairuochen',
    tshirtSize: 'm',
  },
  {
    email: 'jowi.aoun@example.com',
    firstName: 'Jowi',
    lastName: 'Aoun',
    preferredDisplayName: 'Jowi Aoun',
    pronouns: 'he/him',
    mediaUrl: 'https://lh3.googleusercontent.com/pw/AP1GczNMuRR92h4vkYQmh6u5E6pFu7rxvukjlxPSDH7zmwIjPwZEO5y029Ymc_qzaiVTbcQ_UoHpeM90VcRv3wuPscGQsBioyM68Q7Z1C77BfAG_h9RjpTh9KbbhaSHt5iuEHGmn-cLSbz3yAEgOvfwN-rt3=w973-h1460-s-no-gm?authuser=0',
    linkedinHandle: 'jowiaoun',
    tshirtSize: 'm',
  },
  {
    email: 'jeremy.friesen@example.com',
    firstName: 'Jeremy',
    lastName: 'Friesen',
    preferredDisplayName: 'Jeremy Friesen',
    pronouns: 'he/him',
    mediaUrl: 'https://lh3.googleusercontent.com/pw/AP1GczMa8qsig0YI0P_RXELhH3tz1CUH9hKku48quoaBw7F2beMgIHPmO0411YvLwd9EM7Rw4moLzYQUuSHGioJg1yH6n3imC0-Hz7cNB4eMMIEV3oYBMSH4LYqN7SJdTzRqBkDef7KPSB3ODb94D2WgF4G-=w973-h1460-s-no-gm?authuser=0',
    linkedinHandle: 'jeremyfriesen1',
    tshirtSize: 'm',
  },
]
