[build]
command = "pnpm nx build portal"
publish = "/apps/portal/build/client"

[dev]
command = "pnpm nx dev portal"
framework = "vite"
targetPort = 5173
port = 8888

# Set immutable caching for static files, because they have fingerprinted filenames

[[headers]]
for = "/apps/portal/build/*"

[headers.values]

Cache-Control = "public, max-age=31560000, immutable"
