[build]
command = "pnpm nx build website"
publish = "/apps/website/build/client"

[build.environment]
PNPM_FLAGS = "--prod --ignore-scripts"

[dev]
command = "pnpm nx dev website --verbose"
framework = "vite"

# Set immutable caching for static files, because they have fingerprinted filenames

[[headers]]
for = "/apps/website/build/*"

[headers.values]

Cache-Control = "public, max-age=31560000, immutable"
