# fly.toml app configuration file generated for cuhakcing-api on 2025-01-27T20:46:57-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cuhakcing-api'
primary_region = 'yyz'

[build]
dockerfile = 'Dockerfile'

[env]
NODE_ENV = 'production'
PORT = '8080'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = [ 'app' ]

[[vm]]
cpu_kind = 'shared'
cpus = 1
memory_mb = 512
